on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Debug action
    steps:
      - name: Checkout
        uses: actions/checkout@3

      - name: Run action
        uses: ./
        id: go-callvis-action
